### PR TITLE
Avoid horizontal scroll in web-simple

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by kwalrath** [comment]
Thanks, @a14n!

**Comment by kevmoo** [comment]
Merge?

**Comment by kevmoo** [comment]
Oops! Forgot to regenerate. I got it...just FYI for the future `pub run grinder build`

**Comment by a14n** [comment]
Oops sorry, I haven't checked the contribution guide (and I made the change directly on github). Perhaps travis script should check that by regenerating and failed if changes appears.

**Pull request merged**
