### PR TITLE
update to the latest dart sdk stable version

### PR DESCRIPTION
**Pull request by devoncarew**
- update to the latest dart sdk stable version
- rev the pubspec version in prep for publishing

### CODE REVIEW

**Comment by devoncarew** [comment]
One of the newer lints doesn't like the underscore we use for the package name placeholder:

```
Use `lowercase_with_underscores` when specifying a library prefix. • bin/__projectName__.dart:1:58 • library_prefixes
```

**Review by kwalrath — APPROVED** [review]

**Comment by kevmoo** [comment]
> One of the newer lints doesn't like the underscore we use for the package name placeholder:
> 
> ```
> Use `lowercase_with_underscores` when specifying a library prefix. • bin/__projectName__.dart:1:58 • library_prefixes
> ```

This lint has been fixed, I believe – CC @pq 

https://github.com/dart-lang/linter/issues/2331

**Comment by devoncarew** [comment]
Do one of you mind publishing the latest?

**Comment by pq** [comment]
This was fixed as of linter `0.1.124` which should be in `dev`?

**Comment by kwalrath** [comment]
> Do one of you mind publishing the latest?

I can publish.

**Comment by kwalrath** [comment]
Published.

**Pull request merged**
