### PR TITLE
Discontinue package

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/dart-lang/stagehand/issues/671

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @devoncarew @domesticmouse not entirely sure how to version this. Should it actually be 5.0.0?

**Comment by devoncarew** [comment]
> cc @devoncarew @domesticmouse not entirely sure how to version this. Should it actually be 5.0.0?

Good question. My guess is that v4.0.0 is that last non-deprecated version that we want people to use, and v5.0.0 is the version where we deprecate? cc @natebosch

**Comment by natebosch** [comment]
In my opinion deprecating in the current major version is sensible.

I don't know if we have prior experience adding a deprecation warning to a `pub global activate` tool.

**Review by devoncarew — APPROVED** [review]
👍

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
From [the logs](https://github.com/dart-lang/stagehand/pull/704/checks?check_run_id=2639097866#step:7:7), please run `pub run build_runner build` to update the stashed version number.

**Comment by mit-mit** [comment]
@domesticmouse yes, will do.

From an offline discussion with @devoncarew, I'm planning on updating this to be say that Stagehand is "Discontinued", not just deprecated. For the tools that are in the SDK, it makes sense to go through a two step process first deprecating then discontinuing, as discontinuing means the tool is no longer in the SDK. For stagehand, it will be on pub.dev marked discontinued, but you can still run the tool.

WDYT?

**Comment by mit-mit** [comment]
Current build failure seems to also be happening on the master branch:
https://github.com/dart-lang/stagehand/runs/2658002053

**Comment by mit-mit** [comment]
@domesticmouse @devoncarew can you please re-review as this changed substantially?

**Comment by domesticmouse** [comment]
Still LGTM, no idea why the build is breaking. @kevmoo might have some insights.

**Comment by mit-mit** [comment]
Given the build is already broken on master, I'm going to merge.

**Comment by mit-mit** [comment]
@domesticmouse can you please publish? I don't seem to have permissions.

**Comment by domesticmouse** [comment]
Published

**Pull request merged**
