### PR TITLE
prep for publishing 3.3.7

### PR DESCRIPTION
**Pull request by devoncarew**
- prep for publishing 3.3.7

Capture the addition of the new template.

### CODE REVIEW

**Comment by kwalrath** [comment]
We also need to add this template to the README (so it'll show up at https://pub.dev/packages/stagehand and pub.dev/documentation/stagehand).

**Comment by kwalrath** [comment]
Thanks, @devoncarew!

**Comment by kwalrath** [comment]
Do you want to do the release, or do you want me to do it?

**Comment by devoncarew** [comment]
If you can do the release that would be great!

**Comment by kwalrath** [comment]
Done.

**Pull request merged**
