### PR TITLE
Remove angular: enabled: true, use array syntax

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**
No SDK restriction for this.

The only quirk is that this won't work for those on 0.0.14 of the plugin (or newer) without at upgrade. If they are on dev-46 or newer, it will upgrade for them automatically, otherwise they'll have to upgrade manually.

### CODE REVIEW

**Comment by kevmoo** [comment]
Update commit message to include

```
Fixes https://github.com/dart-lang/stagehand/issues/492
```

😁

**Comment by kwalrath** [comment]
The wiki has instructions... somewhere.

**Comment by chalin** [comment]
Or you can just run `./tool/build-check.sh` (which essentially just runs grind and complains if any of the generated files have changed).

**Comment by MichaelRFairhurst** [comment]
ok now seems all in order!

**Pull request merged**
