### PR TITLE
Migrate web-simple template to null-safety

### PR DESCRIPTION
**Pull request by matsp**
Just stumpled over it while testing some ideas.

### CODE REVIEW

**Comment by devoncarew** [comment]
I haven't reviewed this, but this null safe change wasn't already captured in https://github.com/dart-lang/stagehand/pull/696?

**Comment by matsp** [comment]
Nope. Both web templates are affected. If it helps you I can also check the 'stagexl' template.

**Comment by devoncarew** [comment]
Thanks! I added two reviewers; if we need these changes, we should be sure to also apply them to the copy in dart-lang/sdk.

**Comment by devoncarew** [comment]
This will update the sdk version: https://dart-review.googlesource.com/c/sdk/+/194106.

**Review by mit-mit — APPROVED** [review]

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
