### PR TITLE
feat: get email from git config

### PR DESCRIPTION
**Pull request by pd4d10**
Use template for email in `pubspec.yaml`, as same as author

### CODE REVIEW

**Comment by kevmoo** [comment]
@kwalrath ?

**Comment by kwalrath** [comment]
Nice change! Could you please go to https://cla.developers.google.com/about/google-individual and sign the CLA, so we can accept your PR?

**Comment by pd4d10** [comment]
Seems I signed it previously as an individual contributor. Is that OK? @kwalrath

**Comment by kwalrath** [comment]
@pd4d10 for some reason our CLA-checking tool isn't recognizing your GitHub ID. Did you have a different email account when you signed? Did you try signing again?

**Comment by pd4d10** [comment]
@kwalrath The two email addresses are the same.

I clicked '**I Agree**' button at CLA page again. Is the status updated?

**Comment by kwalrath** [comment]
> @kwalrath The two email addresses are the same.
> 
> I clicked '**I Agree**' button at CLA page again. Is the status updated?

Yes! I don't know what the issue was, but we're good to go now.

**Pull request merged**
