### PR TITLE
Stagehand 4.0.0 release paperwork

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by mit-mit** [comment]
Given we changes these to null safety, I don't think we should do this before the next stable release?

**Comment by domesticmouse** [comment]
Yup, I'm happy to hold this PR until the next stable release.

**Comment by domesticmouse** [comment]
@mit-mit can we land this change now?

**Comment by mit-mit** [comment]
Yup!

**Comment by mit-mit** [comment]
@domesticmouse doesn't look like this was published?

**Comment by domesticmouse** [comment]
Whoops. Published now.

**Pull request merged**
