### PR TITLE
Null safety migration for stagehand templates

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by kevmoo** [comment]
Let's get us moved to GitHub actions first – just so cI is a thing

**Comment by domesticmouse** [comment]
My plan is to land this when Dart 2.12 becomes stable. I'm just creating it now to track progress of the underlying null safety migrations.

**Comment by domesticmouse** [comment]
Updated plan, the aim is now to land this PR when `dart create`'s templated apps are converted to null safety.

**Comment by devoncarew** [comment]
> Updated plan, the aim is now to land this PR when `dart create`'s templated apps are converted to null safety.

Just for clarity, the `dart create` templates just use stagehand (from this commit: https://github.com/dart-lang/sdk/blob/master/DEPS#L154).

**Comment by domesticmouse** [comment]
Replaced by https://github.com/dart-lang/stagehand/pull/696

**Pull request closed without merging**
