### PR TITLE
[WIP] Update for Dart 2.6

### PR DESCRIPTION
**Pull request by domesticmouse**
*DO NOT MERGE*

This PR, as it stands, will generate broken projects for developers on Dart SDK v2.5. We can't bring everything up to Dart v2.6 because Flutter Stable still ships with Dart v2.5 embedded in it.

### CODE REVIEW

**Comment by mit-mit** [comment]
@domesticmouse looks like travis is failing?
https://travis-ci.org/dart-lang/stagehand/builds/607596922?utm_medium=notification&utm_source=github_status

**Comment by domesticmouse** [comment]
PTAL @mit-mit, the tests are all green now.

**Comment by kwalrath** [comment]
The question is whether updating the SDK so soon after a release (especially when none of the code depends on 2.6) is helpful to users... @domesticmouse will look into this.

**Comment by domesticmouse** [comment]
Closing this out, I will update `stagehand` when the next stable Flutter is released.

**Pull request closed without merging**
