### PR TITLE
Add tools from .travis.yml

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
Apologies @kevmoo I accidently landed the Github actions directly into master as opposed to a new branch. This PR is to update the default script with tools from the `.travis.yml` configuration.

See https://github.com/dart-lang/stagehand/pull/688 for the travis retirement.

**Review by kevmoo — APPROVED** [review]
Did you verify the output?

Did you delete the travis config yet?

**Comment by domesticmouse** [comment]
Travis was removed in #688. My understanding is that travis is no longer running, so I can't verify against it. I've looked at the checks output and it looks sane to me, e.g. https://github.com/dart-lang/stagehand/pull/689/checks?check_run_id=1810592375, but I was hoping you could review it as well.

**Comment by domesticmouse** [comment]
I'll rectify any missing pieces in a follow up PR

**Pull request merged**
